//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meow.FR.Rincevent.Core.Gui.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class QuizzSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static QuizzSettings defaultInstance = ((QuizzSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new QuizzSettings())));
        
        public static QuizzSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("English")]
        public global::System.Globalization.CultureInfo WritingRecognitionLanguage {
            get {
                return ((global::System.Globalization.CultureInfo)(this["WritingRecognitionLanguage"]));
            }
            set {
                this["WritingRecognitionLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WritingRecognition {
            get {
                return ((bool)(this["WritingRecognition"]));
            }
            set {
                this["WritingRecognition"] = value;
            }
        }
    }
}
