//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meow.FR.Rincevent.Core.Gui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Meow.FR.Rincevent.Core.Gui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Accept {
            get {
                object obj = ResourceManager.GetObject("Accept", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should I add this content ?.
        /// </summary>
        internal static string AddContent {
            get {
                return ResourceManager.GetString("AddContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        internal static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ArrowRight {
            get {
                object obj = ResourceManager.GetObject("ArrowRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt.
        /// </summary>
        internal static string Attempt {
            get {
                return ResourceManager.GetString("Attempt", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Cancel {
            get {
                object obj = ResourceManager.GetObject("Cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ColumnAdd {
            get {
                object obj = ResourceManager.GetObject("ColumnAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ColumnPicture {
            get {
                object obj = ResourceManager.GetObject("ColumnPicture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ColumnPictureXP {
            get {
                object obj = ResourceManager.GetObject("ColumnPictureXP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ColumnRemove {
            get {
                object obj = ResourceManager.GetObject("ColumnRemove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ColumnsAccept {
            get {
                object obj = ResourceManager.GetObject("ColumnsAccept", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ColumnSound {
            get {
                object obj = ResourceManager.GetObject("ColumnSound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ColumnSoundXP {
            get {
                object obj = ResourceManager.GetObject("ColumnSoundXP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ColumnText {
            get {
                object obj = ResourceManager.GetObject("ColumnText", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ColumnTextXP {
            get {
                object obj = ResourceManager.GetObject("ColumnTextXP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CommentEdit {
            get {
                object obj = ResourceManager.GetObject("CommentEdit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore this error and continue?.
        /// </summary>
        internal static string ContinueOrNot {
            get {
                return ResourceManager.GetString("ContinueOrNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct answer.
        /// </summary>
        internal static string CorrectAnswer {
            get {
                return ResourceManager.GetString("CorrectAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A critical error occured. Please contact TigrouMeow on http://www.meow.fr ! Thank you..
        /// </summary>
        internal static string CriticalErrorAndContactMe {
            get {
                return ResourceManager.GetString("CriticalErrorAndContactMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV import module..
        /// </summary>
        internal static string CSV_Description {
            get {
                return ResourceManager.GetString("CSV_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV file.
        /// </summary>
        internal static string CSV_Name {
            get {
                return ResourceManager.GetString("CSV_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current file has modifications. Would you like to save them ?.
        /// </summary>
        internal static string FileHasModifications {
            get {
                return ResourceManager.GetString("FileHasModifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome in Rincevent :o) You should really start by reading the tutorial. You can access it by &apos;Help&apos; -&gt; &apos;Tutorial&apos; ! Happy learning !.
        /// </summary>
        internal static string FirstStartMessage {
            get {
                return ResourceManager.GetString("FirstStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only characters are accepted..
        /// </summary>
        internal static string FrmErrorBadCharacters {
            get {
                return ResourceManager.GetString("FrmErrorBadCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A name is needed (that doesn&apos;t exist already)..
        /// </summary>
        internal static string FrmErrorEmpty {
            get {
                return ResourceManager.GetString("FrmErrorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are columns with the same &apos;order&apos; value .
        /// </summary>
        internal static string FrmSettingsErrorSameOrder {
            get {
                return ResourceManager.GetString("FrmSettingsErrorSameOrder", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap GlobCn {
            get {
                object obj = ResourceManager.GetObject("GlobCn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GlobFr {
            get {
                object obj = ResourceManager.GetObject("GlobFr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GlobUs {
            get {
                object obj = ResourceManager.GetObject("GlobUs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap html_valid {
            get {
                object obj = ResourceManager.GetObject("html_valid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number you typed in invalid. But is it a number?.
        /// </summary>
        internal static string InvalidNumber {
            get {
                return ResourceManager.GetString("InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is either corrupted or not a Rincevent file..
        /// </summary>
        internal static string MainFormLoadError {
            get {
                return ResourceManager.GetString("MainFormLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened in the module. Its execution has been cancelled..
        /// </summary>
        internal static string MainFormModuleError {
            get {
                return ResourceManager.GetString("MainFormModuleError", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap MiniRincevent {
            get {
                object obj = ResourceManager.GetObject("MiniRincevent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pops the data in a small-sizable window with a customized timer..
        /// </summary>
        internal static string MiniWindow_Description {
            get {
                return ResourceManager.GetString("MiniWindow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiniWindow.
        /// </summary>
        internal static string MiniWindow_Name {
            get {
                return ResourceManager.GetString("MiniWindow_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Check All.
        /// </summary>
        internal static string MnuCheckAll {
            get {
                return ResourceManager.GetString("MnuCheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete.
        /// </summary>
        internal static string MnuDelete {
            get {
                return ResourceManager.GetString("MnuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Modify.
        /// </summary>
        internal static string MnuModify {
            get {
                return ResourceManager.GetString("MnuModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Random check / uncheck.
        /// </summary>
        internal static string MnuRandomCheckUncheck {
            get {
                return ResourceManager.GetString("MnuRandomCheckUncheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Rename.
        /// </summary>
        internal static string MnuRename {
            get {
                return ResourceManager.GetString("MnuRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Sort / Unsort.
        /// </summary>
        internal static string MnuSortUnsort {
            get {
                return ResourceManager.GetString("MnuSortUnsort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Uncheck All.
        /// </summary>
        internal static string MnuUncheckAll {
            get {
                return ResourceManager.GetString("MnuUncheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will be enabled on a future release of Rincevent ! Sorry :(.
        /// </summary>
        internal static string NextVersion {
            get {
                return ResourceManager.GetString("NextVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NoButton {
            get {
                return ResourceManager.GetString("NoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no checked items to play. You can either check items or change the parameters to play the unchecked items too..
        /// </summary>
        internal static string NoCheckedItemsToPlay {
            get {
                return ResourceManager.GetString("NoCheckedItemsToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no items to play. Add items to your list !.
        /// </summary>
        internal static string NoItemsToPlay {
            get {
                return ResourceManager.GetString("NoItemsToPlay", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap NoPhoto {
            get {
                object obj = ResourceManager.GetObject("NoPhoto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no unchecked items to play. You can either uncheck items or change the parameters to play the checked items too..
        /// </summary>
        internal static string NoUncheckedItemsToPlay {
            get {
                return ResourceManager.GetString("NoUncheckedItemsToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One output module is needed at least to play the content..
        /// </summary>
        internal static string OneOutputModuleIsNeeded {
            get {
                return ResourceManager.GetString("OneOutputModuleIsNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam and brute-learning module..
        /// </summary>
        internal static string Quizz_Description {
            get {
                return ResourceManager.GetString("Quizz_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quizz.
        /// </summary>
        internal static string Quizz_Name {
            get {
                return ResourceManager.GetString("Quizz_Name", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename this column.
        /// </summary>
        internal static string RenameColumn {
            get {
                return ResourceManager.GetString("RenameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rincevent must be restarted to use the new settings..
        /// </summary>
        internal static string RestartNeeded {
            get {
                return ResourceManager.GetString("RestartNeeded", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Rincevent {
            get {
                object obj = ResourceManager.GetObject("Rincevent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://rincevent.codeplex.com/.
        /// </summary>
        internal static string RinceventUrl {
            get {
                return ResourceManager.GetString("RinceventUrl", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Smartfm {
            get {
                object obj = ResourceManager.GetObject("Smartfm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart.fm list import module..
        /// </summary>
        internal static string SmartFM_Description {
            get {
                return ResourceManager.GetString("SmartFM_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart.fm list.
        /// </summary>
        internal static string SmartFM_Name {
            get {
                return ResourceManager.GetString("SmartFM_Name", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Spinner {
            get {
                object obj = ResourceManager.GetObject("Spinner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon TrayPause {
            get {
                object obj = ResourceManager.GetObject("TrayPause", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon TrayPlay {
            get {
                object obj = ResourceManager.GetObject("TrayPlay", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon TrayStop {
            get {
                object obj = ResourceManager.GetObject("TrayStop", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://rincevent.codeplex.com/Wiki/View.aspx?title=Tutorial.
        /// </summary>
        internal static string TutorialUrl {
            get {
                return ResourceManager.GetString("TutorialUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check this element ?.
        /// </summary>
        internal static string TxtCheckThisElement {
            get {
                return ResourceManager.GetString("TxtCheckThisElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncheck this element ?.
        /// </summary>
        internal static string TxtUncheckThisElement {
            get {
                return ResourceManager.GetString("TxtUncheckThisElement", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap VsAdd {
            get {
                object obj = ResourceManager.GetObject("VsAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsCsv {
            get {
                object obj = ResourceManager.GetObject("VsCsv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsDelete {
            get {
                object obj = ResourceManager.GetObject("VsDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsDeleteItem {
            get {
                object obj = ResourceManager.GetObject("VsDeleteItem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsExit {
            get {
                object obj = ResourceManager.GetObject("VsExit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsFont {
            get {
                object obj = ResourceManager.GetObject("VsFont", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsGo {
            get {
                object obj = ResourceManager.GetObject("VsGo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsHelp {
            get {
                object obj = ResourceManager.GetObject("VsHelp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsHtml {
            get {
                object obj = ResourceManager.GetObject("VsHtml", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsInfo {
            get {
                object obj = ResourceManager.GetObject("VsInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsiPod {
            get {
                object obj = ResourceManager.GetObject("VsiPod", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsLightbulb {
            get {
                object obj = ResourceManager.GetObject("VsLightbulb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsMic {
            get {
                object obj = ResourceManager.GetObject("VsMic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsModule {
            get {
                object obj = ResourceManager.GetObject("VsModule", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsNew {
            get {
                object obj = ResourceManager.GetObject("VsNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsOpen {
            get {
                object obj = ResourceManager.GetObject("VsOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsPause {
            get {
                object obj = ResourceManager.GetObject("VsPause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsPlay {
            get {
                object obj = ResourceManager.GetObject("VsPlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsPlaylist {
            get {
                object obj = ResourceManager.GetObject("VsPlaylist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsPlaylistAdd {
            get {
                object obj = ResourceManager.GetObject("VsPlaylistAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsPlaylistAddChecked {
            get {
                object obj = ResourceManager.GetObject("VsPlaylistAddChecked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsPlaylistChecked {
            get {
                object obj = ResourceManager.GetObject("VsPlaylistChecked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsPlaylistEdit {
            get {
                object obj = ResourceManager.GetObject("VsPlaylistEdit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsPlaylistRemove {
            get {
                object obj = ResourceManager.GetObject("VsPlaylistRemove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsPlaylistRemoveChecked {
            get {
                object obj = ResourceManager.GetObject("VsPlaylistRemoveChecked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsPlaylists {
            get {
                object obj = ResourceManager.GetObject("VsPlaylists", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsPlaylistUnchecked {
            get {
                object obj = ResourceManager.GetObject("VsPlaylistUnchecked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsPrint {
            get {
                object obj = ResourceManager.GetObject("VsPrint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsProperties {
            get {
                object obj = ResourceManager.GetObject("VsProperties", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsQuizz {
            get {
                object obj = ResourceManager.GetObject("VsQuizz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsRecord {
            get {
                object obj = ResourceManager.GetObject("VsRecord", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsRemove {
            get {
                object obj = ResourceManager.GetObject("VsRemove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsRename {
            get {
                object obj = ResourceManager.GetObject("VsRename", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsSave {
            get {
                object obj = ResourceManager.GetObject("VsSave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsSettings {
            get {
                object obj = ResourceManager.GetObject("VsSettings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsShape {
            get {
                object obj = ResourceManager.GetObject("VsShape", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsSort {
            get {
                object obj = ResourceManager.GetObject("VsSort", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vsStar {
            get {
                object obj = ResourceManager.GetObject("vsStar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsStop {
            get {
                object obj = ResourceManager.GetObject("VsStop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsTimer {
            get {
                object obj = ResourceManager.GetObject("VsTimer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VsWorldGo {
            get {
                object obj = ResourceManager.GetObject("VsWorldGo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong ! The right answer was.
        /// </summary>
        internal static string WrongAnswerMsg {
            get {
                return ResourceManager.GetString("WrongAnswerMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string YesButton {
            get {
                return ResourceManager.GetString("YesButton", resourceCulture);
            }
        }
    }
}
