//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meow.FR.Rincevent.Core.Gui.Modules.MiniWindow.Configuration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ModuleSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModuleSettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Meow.FR.Rincevent.Core.Gui.Modules.MiniWindow.Configuration.ModuleSettings", typeof(ModuleSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _General.
        /// </summary>
        internal static string _General {
            get {
                return ResourceManager.GetString("_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoScroll enabled.
        /// </summary>
        internal static string AutoScroll {
            get {
                return ResourceManager.GetString("AutoScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies either or not the different values should be displayed without any user&apos;s actions..
        /// </summary>
        internal static string AutoScrollDescription {
            get {
                return ResourceManager.GetString("AutoScrollDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoScroll delay.
        /// </summary>
        internal static string AutoScrollTimer {
            get {
                return ResourceManager.GetString("AutoScrollTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the time to wait before scrolling to the next value (within the same popup)..
        /// </summary>
        internal static string AutoScrollTimerDescription {
            get {
                return ResourceManager.GetString("AutoScrollTimerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discreet.
        /// </summary>
        internal static string Discreet {
            get {
                return ResourceManager.GetString("Discreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets either to hide or not the window when there is no data to display..
        /// </summary>
        internal static string DiscreetDescription {
            get {
                return ResourceManager.GetString("DiscreetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font AutoSize.
        /// </summary>
        internal static string FontAutoSize {
            get {
                return ResourceManager.GetString("FontAutoSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of the text will be adapted to fit to the window..
        /// </summary>
        internal static string FontAutoSizeDescription {
            get {
                return ResourceManager.GetString("FontAutoSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        internal static string Opacity {
            get {
                return ResourceManager.GetString("Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the opacity percentage of the popup window..
        /// </summary>
        internal static string OpacityDescription {
            get {
                return ResourceManager.GetString("OpacityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the window&apos;s position on the screen..
        /// </summary>
        internal static string PositionDescription {
            get {
                return ResourceManager.GetString("PositionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the size of the window..
        /// </summary>
        internal static string SizeDescription {
            get {
                return ResourceManager.GetString("SizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer.
        /// </summary>
        internal static string Timer {
            get {
                return ResourceManager.GetString("Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the time between each popup. The value is in seconds..
        /// </summary>
        internal static string TimerDescription {
            get {
                return ResourceManager.GetString("TimerDescription", resourceCulture);
            }
        }
    }
}
